// budget-app/src/components/Nav.vue
<template>
  <nav>
    <router-link to="/money" class="item">
      <Icon name="money"/>
      New
    </router-link>

    <router-link to="/labels" class="item">
      <Icon name="label"/>
      Tags
    </router-link>

    <router-link to="/statistics" class="item">
      <Icon name="statistics"/>
      Statistics
    </router-link>
  </nav>
</template>

<script lang="ts">

export default {
  name: "Nav"
}
</script>

<style lang="scss" scoped>

nav {
  display: flex;
  box-shadow: 0 0 8px rgba(0, 0, 0, 0.25);
  flex-direction: row;

  .item {
    margin: 10px 0;
    width:33.33333%;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    color: #7a7979;
  }
  .icon{
    width: 30px;
    height: 30px;
    margin-bottom: 2px;
  }
}
</style>

// react-accounting-app/src/components/Nav.tsx
import {Link} from "react-router-dom";
import styled from "styled-components";

const NavWrapper = styled.nav`
  box-shadow: 0 0 3px rgba(0, 0, 0, 0.25);
  line-height: 24px;

  > ul {
    display: flex;
    justify-content: space-around;

    > li {
      text-align: center;
      padding: 16px;
    }
  }
`

const Nav = () => {
    return (
        <NavWrapper>
            <ul>
                <li>
                    <Link to="/tags">Tags</Link>
                </li>
                <li>
                    <Link to="/money">Money</Link>
                </li>
                <li>
                    <Link to="/statistics">Statistics</Link>
                </li>
            </ul>
        </NavWrapper>
    )
}


export default Nav;
